backend:
  name: git-gateway
  repo: Addie1212/aelc-website
  branch: main
  identity_url: https://auth.decapbridge.com

media_folder: "images"
public_folder: "/images"

collections:
  - name: "pages"
    label: "Pages"
    folder: "content"
    create: true
    slug: "{{slug}}"
    fields:
      - {label: "Title", name: "title", widget: "string"}
      - {label: "Body", name: "body", widget: "markdown"}
